package main

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/BurntSushi/toml"
)

const packagesRel = ".local/share/hatch/packages.sh"

func runQuiet(name string, args ...string) ([]byte, error) {
	if _, err := exec.LookPath(name); err != nil {
		return nil, err
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	return exec.CommandContext(ctx, name, args...).Output()
}

func shq(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// homeArg keeps the script portable when the new machine has a different username.
func homeArg(home, p string) string {
	if rel, err := filepath.Rel(home, p); err == nil && !strings.HasPrefix(rel, "..") && !filepath.IsAbs(rel) {
		return `"$HOME"/` + shq(filepath.ToSlash(rel))
	}
	return shq(p)
}

func (s *scanner) scanPackages() {
	type section struct {
		label string
		cmds  []string
	}
	var sections []section
	if _, err := os.Stat(filepath.Join(s.home, ".config", "mise")); err == nil {
		if _, err := exec.LookPath("mise"); err == nil {
			sections = append(sections, section{"mise", []string{"mise install"}})
		}
	}
	if out, err := runQuiet("cargo", "install", "--list"); err == nil {
		sections = append(sections, section{"cargo", cargoCmds(string(out), s.home)})
	}
	sections = append(sections, section{"go", s.goCmds()})
	if out, err := runQuiet("npm", "ls", "-g", "--depth=0", "--json"); err == nil {
		sections = append(sections, section{"npm", npmCmds(out)})
	}
	if out, err := runQuiet("pipx", "list", "--json"); err == nil {
		sections = append(sections, section{"pipx", pipxCmds(out, s.home)})
	}
	sections = append(sections, section{"uv", uvCmds(s.home)})

	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	fmt.Fprintf(&b, "# generated by hatch on %s: reinstall tools installed outside Homebrew\n", hostName())
	b.WriteString("set -u\nFAILED=0\nfailed() { echo \"hatch: failed: $*\" >&2; FAILED=$((FAILED+1)); }\n")
	var counts []string
	for _, sec := range sections {
		if len(sec.cmds) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n# %s\n", sec.label)
		for _, c := range sec.cmds {
			fmt.Fprintf(&b, "%s || failed %s\n", c, shq(sec.label+" "+installTarget(c)))
		}
		if sec.label != "mise" {
			counts = append(counts, fmt.Sprintf("%d %s", len(sec.cmds), sec.label))
		}
	}
	if len(counts) == 0 {
		return
	}
	b.WriteString("\n[ \"$FAILED\" -eq 0 ] || { echo \"hatch: $FAILED installs failed\" >&2; exit 1; }\n")
	s.add(&source{
		Item:  Item{ID: "packages", Kind: KindBrew, Label: "reinstall script", Path: packagesRel, Detail: strings.Join(counts, " · ")},
		files: []fileEntry{{rel: packagesRel, data: []byte(b.String()), size: int64(b.Len()), mode: 0o755}},
	})
}

// installTarget recovers the package from a generated command for the
// failure message: its last argument, unquoted.
func installTarget(cmd string) string {
	i := strings.LastIndex(cmd, " ")
	t := cmd[i+1:]
	t = strings.TrimPrefix(t, `"$HOME"/`)
	return strings.ReplaceAll(strings.Trim(t, "'"), `'\''`, "'")
}

// cargoCmds parses `cargo install --list`: crate header lines look like
// "name v1.2.3:", "name v1.2.3 (https://host/repo#rev):" or "name v1.2.3 (/path):".
func cargoCmds(out, home string) []string {
	var cmds []string
	sc := bufio.NewScanner(strings.NewReader(out))
	for sc.Scan() {
		line := sc.Text()
		if line == "" || line[0] == ' ' || line[0] == '\t' {
			continue
		}
		line = strings.TrimSuffix(line, ":")
		name, rest, _ := strings.Cut(line, " ")
		src := ""
		if i := strings.Index(rest, "("); i >= 0 {
			src = strings.TrimSuffix(rest[i+1:], ")")
		}
		switch {
		case strings.HasPrefix(src, "http"), strings.HasPrefix(src, "git"):
			url, _, _ := strings.Cut(src, "#")
			cmds = append(cmds, "cargo install --git "+shq(url)+" "+shq(name))
		case strings.HasPrefix(src, "/"):
			cmds = append(cmds, "cargo install --path "+homeArg(home, src))
		default:
			cmds = append(cmds, "cargo install "+shq(name))
		}
	}
	return cmds
}

func (s *scanner) goCmds() []string {
	if _, err := exec.LookPath("go"); err != nil {
		return nil
	}
	var dirs []string
	if out, err := runQuiet("go", "env", "GOBIN", "GOPATH"); err == nil {
		lines := strings.Split(strings.TrimSpace(string(out)), "\n")
		if len(lines) > 0 && strings.TrimSpace(lines[0]) != "" {
			dirs = append(dirs, strings.TrimSpace(lines[0]))
		}
		if len(lines) > 1 && strings.TrimSpace(lines[1]) != "" {
			dirs = append(dirs, filepath.Join(strings.TrimSpace(lines[1]), "bin"))
		}
	}
	seen := map[string]bool{}
	var cmds []string
	for _, dir := range dirs {
		entries, _ := os.ReadDir(dir)
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			out, err := runQuiet("go", "version", "-m", filepath.Join(dir, e.Name()))
			if err != nil {
				continue
			}
			if c, ok := goInstallCmd(string(out)); ok && !seen[c] {
				seen[c] = true
				cmds = append(cmds, c)
			}
		}
	}
	sort.Strings(cmds)
	return cmds
}

// goInstallCmd skips toolchain binaries (cmd/...) and local builds, which
// report a "(devel)" module version and can't be fetched by path.
func goInstallCmd(versionOut string) (string, bool) {
	var pkg, modVersion string
	sc := bufio.NewScanner(strings.NewReader(versionOut))
	for sc.Scan() {
		f := strings.Fields(sc.Text())
		if len(f) >= 2 && f[0] == "path" {
			pkg = f[1]
		}
		if len(f) >= 3 && f[0] == "mod" {
			modVersion = f[2]
		}
	}
	if pkg == "" || strings.HasPrefix(pkg, "cmd/") || pkg == "command-line-arguments" || !strings.Contains(pkg, ".") || modVersion == "(devel)" {
		return "", false
	}
	return "go install " + shq(pkg+"@latest"), true
}

func npmCmds(out []byte) []string {
	var tree struct {
		Dependencies map[string]json.RawMessage `json:"dependencies"`
	}
	if json.Unmarshal(out, &tree) != nil {
		return nil
	}
	var cmds []string
	for name := range tree.Dependencies {
		if name == "npm" || name == "corepack" {
			continue
		}
		cmds = append(cmds, "npm install -g "+shq(name))
	}
	sort.Strings(cmds)
	return cmds
}

func pipxCmds(out []byte, home string) []string {
	var list struct {
		Venvs map[string]struct {
			Metadata struct {
				MainPackage struct {
					PackageOrURL string   `json:"package_or_url"`
					PipArgs      []string `json:"pip_args"`
				} `json:"main_package"`
			} `json:"metadata"`
		} `json:"venvs"`
	}
	if json.Unmarshal(out, &list) != nil {
		return nil
	}
	var cmds []string
	for _, v := range list.Venvs {
		mp := v.Metadata.MainPackage
		if mp.PackageOrURL == "" {
			continue
		}
		editable := false
		for _, a := range mp.PipArgs {
			if a == "--editable" || a == "-e" {
				editable = true
			}
		}
		target := shq(mp.PackageOrURL)
		if filepath.IsAbs(mp.PackageOrURL) {
			target = homeArg(home, mp.PackageOrURL)
		}
		if editable {
			cmds = append(cmds, "pipx install --editable "+target)
		} else {
			cmds = append(cmds, "pipx install "+target)
		}
	}
	sort.Strings(cmds)
	return cmds
}

func uvCmds(home string) []string {
	receipts, _ := filepath.Glob(filepath.Join(home, ".local", "share", "uv", "tools", "*", "uv-receipt.toml"))
	var cmds []string
	for _, r := range receipts {
		var rc struct {
			Tool struct {
				Requirements []map[string]any `toml:"requirements"`
				Python       string           `toml:"python"`
			} `toml:"tool"`
		}
		if _, err := toml.DecodeFile(r, &rc); err != nil || len(rc.Tool.Requirements) == 0 {
			continue
		}
		req := rc.Tool.Requirements[0]
		str := func(k string) string { v, _ := req[k].(string); return v }
		cmd := "uv tool install"
		if rc.Tool.Python != "" {
			cmd += " --python " + shq(rc.Tool.Python)
		}
		switch {
		case str("editable") != "":
			cmd += " --editable " + homeArg(home, str("editable"))
		case str("directory") != "":
			cmd += " " + homeArg(home, str("directory"))
		case str("git") != "":
			cmd += " " + shq("git+"+str("git"))
		case str("name") != "":
			cmd += " " + shq(str("name"))
		default:
			continue
		}
		cmds = append(cmds, cmd)
	}
	sort.Strings(cmds)
	return cmds
}
