package main

var words = []string{
	"acid", "acorn", "actor", "adobe", "agent", "alarm", "album", "alpha",
	"amber", "angle", "anvil", "apple", "april", "apron", "arena", "arrow",
	"aspen", "atlas", "atom", "attic", "audio", "aurora", "avocado", "axis",
	"bacon", "badge", "bagel", "baker", "bamboo", "banjo", "barrel", "basil",
	"beacon", "beetle", "bench", "berry", "bison", "blade", "blaze", "blimp",
	"bloom", "bongo", "bonus", "boot", "brick", "bridge", "broom", "bubble",
	"bucket", "buffalo", "bugle", "cabin", "cactus", "camel", "candle", "canoe",
	"canyon", "carbon", "cargo", "carpet", "castle", "cedar", "cello", "chalk",
	"cherry", "chess", "cider", "cinema", "circus", "citrus", "clover", "cobalt",
	"cocoa", "comet", "coral", "cosmos", "cotton", "coyote", "crane", "crater",
	"crayon", "cricket", "crown", "cube", "cycle", "dahlia", "daisy", "delta",
	"denim", "desert", "diesel", "dingo", "disco", "dolphin", "domino", "donut",
	"dragon", "drum", "dune", "eagle", "easel", "echo", "eclipse", "elbow",
	"ember", "emerald", "engine", "falcon", "fable", "feather", "fender", "ferret",
	"fiddle", "fig", "flame", "flute", "fossil", "fox", "galaxy", "garlic",
	"gecko", "geyser", "ginger", "glacier", "globe", "goblin", "gopher", "granite",
	"grape", "gravel", "guitar", "hammer", "harbor", "harp", "hazel", "helium",
	"hermit", "hippo", "honey", "hornet", "husky", "igloo", "indigo", "iris",
	"island", "ivory", "jacket", "jaguar", "jasmine", "jelly", "jigsaw", "jungle",
	"kayak", "kernel", "kettle", "kiwi", "koala", "lagoon", "lantern", "laser",
	"lemon", "lentil", "lilac", "lime", "llama", "lobster", "locket", "lotus",
	"magnet", "mango", "maple", "marble", "meadow", "melon", "meteor", "mint",
	"mirror", "mocha", "monsoon", "moose", "mosaic", "motor", "muffin", "nebula",
	"nectar", "needle", "nickel", "noodle", "nova", "nutmeg", "oasis", "ocean",
	"olive", "onyx", "opal", "orbit", "orchid", "otter", "oyster", "paddle",
	"panda", "papaya", "parrot", "pebble", "pepper", "piano", "pickle", "pilot",
	"pixel", "planet", "plasma", "pogo", "polar", "poppy", "prism", "puffin",
	"pumpkin", "quartz", "quill", "rabbit", "radar", "radish", "raven", "reef",
	"rhino", "ribbon", "rocket", "rodeo", "saddle", "saffron", "salmon", "satin",
	"sierra", "silver", "sphinx", "spiral", "sprout", "squid", "tango", "temple",
	"thunder", "tiger", "tofu", "topaz", "tornado", "tulip", "tundra", "turtle",
	"ukulele", "umbrella", "velvet", "violin", "volcano", "walnut", "willow", "zebra",
}
